Class fbt.Pass Extends %Persistent
{

Storage Default
{
<Data name="PassDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^fbt.PassD</DataLocation>
<DefaultData>PassDefaultData</DefaultData>
<IdLocation>^fbt.PassD</IdLocation>
<IndexLocation>^fbt.PassI</IndexLocation>
<StreamLocation>^fbt.PassS</StreamLocation>
<Type>%Library.CacheStorage</Type>
}

}